---
- hosts: localhost
  vars_files:
    - mypass
  tasks:
  - name: Sending an email using Ansible
    mail:
      host: smtp.gmail.com
      port: 587
      username: "sender's gmail id"
      password: "Passwd"  # This password is Generated in gmail (Other App password section in gmail)
      to: "name of reciever <reciever gmail Id>"
      subject: Email By Ansible
      body: Test successful

